### ISSUE TITLE
server configuration

### ISSUE THREAD

**Issue by Sxtanna** [GoLangMc/minecraft-server#2]
decide on configuration style.

**Comment by Sxtanna** [comment]
```toml
[Display]
  motd = "A GoMc Server"

[Version]
  version = "1.15.2"

[Network]
  host = "0.0.0.0"
  port = 25565
```

I personally would like to use TOML
